name: NPM CI

on:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  npm-ci:
    name: NPM CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Check for changes in package files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            packages:
              - 'package.json'
              - 'package-lock.json'

      - name: Setup Node
        if: steps.filter.outputs.packages == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install correct NPM version
        if: steps.filter.outputs.packages == 'true'
        run: npm install -g npm@11

      - name: NPM CI
        if: steps.filter.outputs.packages == 'true'
        run: npm ci --quiet --no-fund --no-audit
